name: Docker Extract
description: Extract file(s) from a Docker Image
branding:
  icon: download
  color: yellow
inputs:
  image:
    description: Docker Image to extract files from
    required: true
  sources:
    description: Path(s) to a file or directory from the image.  Relative paths are relative to the image's working directory.
    required: true
  destination:
    description: Destination path for the extracted files
    required: true
    default: dist
  cleanup:
    description: Remove the container after extracting files
    required: false
    default: true
  follow-link:
    description: Always follow symbol link in `sources`
    required: false
    default: false
outputs:
  destination:
    description: Destination of extracted file(s)
runs:
  using: node20
  main: dist/index.js
